### PR TITLE
[#47] [Android] [UI] As a user, I can see a rating answer

### LINKED ISSUE #47: [Android] [UI] As a user, I can see a rating answer
# Why

User can answer a question with a rating.

# Acceptance Criteria

- Show the range emoji.
- Show the emoji type based on the question's `display_type` (star, heart) and `pick` is `one`

Image

[Figma](https://www.figma.com/file/GjRPOjDyZ6f4EDL3wKarRK/Challenge---Mobile-App?node-id=34-816&t=1xiBQA7GNv0kEx7j-0)

### PR DESCRIPTION
**Pull request by AVI5HEK**
- Close #47 

## What happened 👀

- Show the range emoji.
- Show the emoji type based on the question's display_type (star, heart) and pick is one

## Insight 📝

- Added the RatingBar composable for showing the emoji ratings.

## Proof Of Work 📹

https://github.com/nimblehq/avishek-phong-kmm-ic/assets/8093908/a1507ed0-5d64-42aa-9089-f4046ec2907e

### CODE REVIEW

**Review by kaungkhantsoe — APPROVED** [review]
@AVI5HEK Detekt error 🤚 , the rest are LGTM.

**Review by suho — APPROVED** [review]

**Comment by phongvhd93** [comment]
@AVI5HEK, please the the detek error so I can merge this PR

**Comment by AVI5HEK** [comment]
> @AVI5HEK, please the the detek error so I can merge this PR

Please wait until #134 is merged. All these PRs from here and onward depend on that one. 😓

**Comment by AVI5HEK** [comment]
@phongvhd93 the PR is ready to merge. 🚀

**Pull request merged**
