### PR TITLE
[#4] Set up CI/CD workflow for testing a PR - Part 1 - Testing the iOS app

### LINKED ISSUE #4: [Chore] Set up CI/CD workflow for testing a PR
# Why

To use GitHub Actions to build and test a PR, the machine must be able to run the KMM application.

# Acceptance Criteria

- A test workflow will be triggered when a PR is created and updated.
- The CI machine must be able to test cases in the `shared` project.
- Code coverage will be added to the PR by a bot.

### PR DESCRIPTION
**Pull request by phongvhd93**
- Close #4

## What happened 👀

- Create a workflow for testing the `shared` module and the iOS app.
- Configure Danger for reporting code coverage and lint errors

## Insight 📝

When a developer creates/updates a PR, an automatic code review workflow will be triggered to do the code review and testing of that PR.

## Proof Of Work 📹

This PR is the POW

### CODE REVIEW

**Review by markgravity — COMMENTED** [review]
Please ignore the `fastlane` folder from Danger 🙏

**Comment by phongvhd93** [comment]
> Please ignore the `fastlane` folder from Danger 🙏

@markgravity, I already added it into ignore list in `.swiftlint.yml` and `Dangerfile` (`swiftformat` configuration)

**Comment by markgravity** [comment]
> > Please ignore the `fastlane` folder from Danger 🙏
> 
> @markgravity, I already added it into ignore list in `.swiftlint.yml` and `Dangerfile` (`swiftformat` configuration)

CleanShot 2023-04-13 at 14 45 44
How about these comments? 🤔

**Comment by phongvhd93** [comment]
> > > Please ignore the `fastlane` folder from Danger 🙏
> > 
> > 
> > @markgravity, I already added it into ignore list in `.swiftlint.yml` and `Dangerfile` (`swiftformat` configuration)
> 
> CleanShot 2023-04-13 at 14 45 44 How about these comments? 🤔

- Please check the `.swfitlint` file. It was added before I added fastlane folder to ignore the list, and it was outdated as well. You can check this [PR](https://github.com/nimblehq/avishek-phong-kmm-ic/pull/70); there is no linter error related to `fastlane` folder.

**Review by suho — APPROVED** [review]

**Review by markgravity — APPROVED** [review]

**Pull request merged**
